# <center>Тема 1.1
## <center>Бібліотека NumPy

- **NumPy** (Numeric Python) - це бібліотека мови Python, яка додає підтримку великих багатовимірних масивів і матриць, разом з бібліотекою високорівневих (і дуже швидкодіючих) математичних функцій для операцій з цими масивами.

Для початку роботи з NumPy його, як і будь-який модуль, потрібно імпортувати.

In [2]:
import numpy as np

### <center>Об'єкти ndarray

**numpy.ndarray** - це однорідний багатовимірний масив елементів одного типу. Об'єкти **ndarray** є основними об'єктами NumPy.

Найбільш важливі атрибути об'єктів **ndarray**:
- `ndarray.ndim` - розмірність масиву. Дуже часто один вимір масиву називають "вісь". Наприклад, одновимірний масив в термінології NumPy має одну вісь. Двовимірний - дві осі (стовпці та рядки), тривимірний - три осі тощо.

- `ndarray.shape` - розміри масиву, його форма. Це кортеж натуральних чисел, який показує довжину масиву по кожній осі. Для матриці з **n** рядків і **m** стовпів, `shape` буде **(n, m)**. Число елементів кортежу `shape` дорівнює `ndim`.

- `ndarray.size` - кількість елементів масиву. Очевидно, дорівнює добутку всіх елементів атрибута `shape`.

- `ndarray.dtype` - об'єкт, що описує тип елементів масиву. Можна визначити `dtype`, використовуючи стандартні типи даних Python. NumPy тут надає величезну кількість  можливостей, як вбудованих, (наприклад: `bool_, character, int8, int16, int32, int64, float8, float16, float32, float64, complex64, object_,`) так і можливість визначити власні типи даних, навіть складені (комбіновані).

- `ndarray.itemsize` - розмір кожного елемента масиву в байтах.

- `ndarray.data` - буфер, який містить фактичні елементи масиву. Зазвичай не потрібно використовувати цей атрибут, так як звертатися до елементів масиву найпростіше за допомогою індексів.

### <center>Створення масивів

У NumPy існує багато способів створити масив. Один з найбільш простих - створити масив зі звичайних списків або кортежів Python, використовуючи функцію `numpy.array()` (запам'ятайте: `array()` - функція, що створює об'єкт типу `ndarray`).

In [7]:
a = np.array([1, 2, 3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


Функція `array()` трансформує вкладені послідовності в багатовимірні масиви. Тип елементів масиву залежить від типу елементів початкової послідовності (але можна і перевизначити його під час створення).

In [9]:
b = np.array([[1.5, 2, 3], [4, 5, 6]])
print(b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [11]:
b = np.array([[1.5, 2, 3], [4, 5, 6]], dtype=np.int)
print(b)

[[1 2 3]
 [4 5 6]]


Функція `array()` - не єдина функція для створення масивів. Зазвичай елементи масиву на початку роботи невідомі, а масив, в якому вони будуть зберігатися, вже потрібен. Тому є кілька функцій для того, щоб створювати вже заповнені якимись даними масиви (за замовчуванням тип створюваного масиву - `float64`).

Функція `zeros()` - створює масив з нулів, а функція `ones()` - масив з одиниць. Обидві функції приймають кортеж з розмірами `shape`, і необов'язковий аргумент `dtype`:
- `zeros(shape [, dtype])`
- `ones(shape [, dtype])`

In [13]:
print(np.zeros((3, 5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
print(np.ones((2, 2, 2)))

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


Функція `eye(n)` - створює одиничну матрицю (двовимірний масив).

In [15]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Функція `empty(shape)` - створює масив без його заповнення. Початковий вміст є випадковим і залежить від стану пам'яті на момент створення масиву (тобто від того сміття, що в ній зберігається).

In [16]:
print(np.empty((3, 3)))

[[0.000e+000 0.000e+000 0.000e+000]
 [0.000e+000 0.000e+000 5.613e-321]
 [0.000e+000 0.000e+000 0.000e+000]]


Функція `arange(i [, j, k])` - аналогічна вбудованій в Python функції `range()`, тільки замість списків вона повертає масиви, і приймає не лише цілі значення.

In [18]:
print(np.arange(10, 30, 5))
print(np.arange(0, 1, 0.1))

[10 15 20 25]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


**Увага!** Під час використання `arange()` з аргументами типу `float`, може виникнути невизначеність в тому, скільки елементів буде отримано (через обмеження точності чисел з плаваючою комою). Тому, в таких випадках зазвичай краще використовувати функцію `linspace()`, яка замість кроку в якості одного з аргументів приймає число, що дорівнює кількості потрібних елементів.

In [20]:
# 9 чисел від 0 до 2 включно
print(np.linspace(0, 2, 9))

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


Функція `fromfunction(f, i, j)` - застосовує деяку функцію **f** до всіх комбінацій індексів **i, j**.

In [26]:
def f1(i, j):
    return 3 * i + j

In [27]:
print(np.fromfunction(f1, (3, 4)))
print()
print(np.fromfunction(f1, (3, 3)))

[[0. 1. 2. 3.]
 [3. 4. 5. 6.]
 [6. 7. 8. 9.]]

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


### <center>Вивід масивів

Якщо масив занадто великий, щоб його повністю показати, NumPy автоматично приховує центральну частину масиву і виводить тільки його кути.

In [52]:
print(np.arange(0, 3000, 1))

[   0    1    2 ... 2997 2998 2999]


Функція `set_printoptions()` дозволяє вивести більше елементів. Для цього потрібно вказати значення параметру `threshold`, яке і буде вказувати інтерпретатору на те, скільки можна виводити елементів масиву без скорочення запису.

In [53]:
np.set_printoptions(threshold = 100)
print(np.arange(0, 100, 1))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


### <center>Базові операції над масивами

Математичні операції над масивами NumPy виконуються поелементно (масиви повінні мати однакові розміри). В результаті створюється новий масив, який заповнюється результатами операції.

In [4]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)

In [4]:
print(a + b)

[20 31 42 53]


In [5]:
print(a - b)

[20 29 38 47]


In [6]:
print(a * b)

[  0  30  80 150]


In [7]:
print(a / b)
# У випадку ділення на нуль виникне попередження, а результатом буде константа inf - нескінченність

[        inf 30.         20.         16.66666667]


C:\Users\drewmt\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [8]:
print(a ** b)

[     1     30   1600 125000]


In [9]:
print(a % b)
# остача від ділення на 0 буде дорівнювати 0

[0 0 0 2]


C:\Users\drewmt\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in remainder
  """Entry point for launching an IPython kernel.


Якщо розміри масивів будуть різними, виникне помилка.

In [10]:
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[1, 2], [3, 4], [5, 6]])
print(c + d)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

Можна виконувати поелементні операції із масивом та одним числом.

In [12]:
print(a + 1)
print(a ** 3)

[21 31 41 51]
[  8000  27000  64000 125000]


А також виконувати фільтрацію - результатом буде масив булевих значень.

In [14]:
print(a < 35)

[ True  True False False]


Доступна велика кількість математичних операцій для обробки масивів. Повний список за посиланням: https://docs.scipy.org/doc/numpy/reference/routines.math.html

In [16]:
print(np.cos(a))

[ 0.40808206  0.15425145 -0.66693806  0.96496603]


In [18]:
print(np.tan(a))

[ 2.23716094 -6.4053312  -1.11721493 -0.27190061]


In [19]:
print(np.exp(a))

[4.85165195e+08 1.06864746e+13 2.35385267e+17 5.18470553e+21]


In [5]:
print(np.sqrt(a))

[4.47213595 5.47722558 6.32455532 7.07106781]


Доступні операції округлення:

In [29]:
c = np.array([1.5, 1.33, 1.66])
print(np.round_(c))
print(np.floor(c))
print(np.ceil(c))

[2. 1. 2.]
[1. 1. 1.]
[2. 2. 2.]


Багато операцій, таких як, наприклад, обчислення суми всіх елементів масиву, представлені також і у вигляді методів класу **ndarray**.

In [30]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [33]:
print(np.sum(a))
# Можна записати у вигляді виклику методу класу
print(a.sum())

21
21


In [35]:
# Знаходження мінімального та максимального елемента
print(a.min())
print(a.max())

1
6


За замовчуванням, ці операції застосовуються до всього масиву, незалежно від його форми. Однак, вказавши параметр `axis`, можна застосувати операцію для зазначеної вісі масиву.

In [37]:
# Мінімальне число в кожному стовпці
print(a.min(axis=0))
# Мінімальне число в кожному рядку
print(a.min(axis=1))

[1 2 3]
[1 4]


### <center>Індекси та зрізи

В NumPy робота з індексами та зрізами масивів виконується так само, як і зі звичайними послідовностями у Python.

In [6]:
a = np.arange(10) ** 3
print(a)

[  0   1   8  27  64 125 216 343 512 729]


In [8]:
print(a[1])
print(a[3:7])

1
[ 27  64 125 216]


In [9]:
a[3:7] = 8
print(a)

[  0   1   8   8   8   8   8 343 512 729]


In [10]:
print(a[::-1])

[729 512 343   8   8   8   8   8   1   0]


Обхід масивів в циклах відбувається так само, як і для звичайних послідовностей у Python.

In [12]:
for i in a:
    print(i ** 2)

0
1
64
64
64
64
64
117649
262144
531441


У багатовимірних масивах кожній осі відповідає один індекс. Індекси передаються у вигляді послідовності чисел, розділених комами (тобто, кортежами).

In [13]:
b = np.array([[  0, 1, 2, 3],
            [10, 11, 12, 13],
            [20, 21, 22, 23],
            [30, 31, 32, 33],
            [40, 41, 42, 43]])

In [15]:
# Вивід елемента, який знаходиться у рядку з індексом 2 та стовпці з індексом 3 (пам'ятаємо, що нумерація починається з 0)
print(b[2,3])
# або у іншій формі запису
print(b[2][3])

23
23


In [23]:
# Вивід стовпця з індексом 2
print(b[:,2])

[ 2 12 22 32 42]


In [24]:
# Вивід перших двох рядків
print(b[:2])

[[ 0  1  2  3]
 [10 11 12 13]]


In [25]:
# Вивід рядків з індексами 1 та 2
print(b[1:3, : : ])

[[10 11 12 13]
 [20 21 22 23]]


In [26]:
# Вивід останнього рядка
print(b[-1])

[40 41 42 43]


`b[i]` можна читати як `b[i, <стільки символів ':', скільки потрібно>]`. В NumPy це також можна записати за допомогою крапок, у вигляді `b[i, ...]`.

Наприклад, якщо `x` має ранг 5 (тобто у нього 5 осей), тоді:

- `x[1, 2, ...]` еквівалентно `x[1, 2, :, :, :]`,
- `x[... , 3]` те саме, що `x[:, :, :, :, 3]`,
- `x[4, ... , 5, :]` це `x[4, :, :, 5, :]`.

In [27]:
a = np.array(([[0, 1, 2], [10, 12, 13]], [[100, 101, 102], [110, 112, 113]]))
print(a)
print(a.shape)

[[[  0   1   2]
  [ 10  12  13]]

 [[100 101 102]
  [110 112 113]]]
(2, 2, 3)


In [30]:
print(a[1, ...]) # те саме, що a[1, : , :] або a[1]

[[100 101 102]
 [110 112 113]]


Ітерування багатовимірних масивів починається з першої осі.

In [31]:
for row in a:
    print(row)

[[ 0  1  2]
 [10 12 13]]
[[100 101 102]
 [110 112 113]]


Однак, якщо потрібно перебрати поелементно весь масив, ніби він є одновимірним, для цього можна використовувати атрибут `flat`:

In [32]:
for el in a.flat:
    print(el)

0
1
2
10
12
13
100
101
102
110
112
113


### <center>Операції з формою масивів

Як вже було сказано, масив має форму (`shape`), яка визначається числом елементів вздовж кожної осі.

In [33]:
print(a)
print(a.shape)

[[[  0   1   2]
  [ 10  12  13]]

 [[100 101 102]
  [110 112 113]]]
(2, 2, 3)


Форма масиву може бути змінена за допомогою різних команд.

In [35]:
# Зробити масив плоским
print(a.ravel())

[  0   1   2  10  12  13 100 101 102 110 112 113]


In [36]:
# Змінити форму масиву (початковий масив змінюється)
a.shape = (6, 2)
print(a)

[[  0   1]
 [  2  10]
 [ 12  13]
 [100 101]
 [102 110]
 [112 113]]


In [42]:
# Транспонування
print(a.T)

[[  0   2  12 100 102 112]
 [  1  10  13 101 110 113]]


In [46]:
# Зміна форми (початковий масив не змінєються)
print(a.reshape((3, 4)))

[[  0   1   2  10]
 [ 12  13 100 101]
 [102 110 112 113]]


In [49]:
# Зміна форми (початковий масив змінюється)
a.resize((2, 6))
print(a)

[[  0   1   2  10  12  13]
 [100 101 102 110 112 113]]


### <center>Об'єднання масивів

Декілька масивів можуть бути об'єднані в один уздовж різних осей за допомогою функцій `hstack()` і `vstack()`.
- `hstack()` об'єднує масиви за першими осями, `vstack()` - за останніми.

In [54]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(a)
print()
print(b)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]


In [52]:
print(np.vstack((a, b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [51]:
print(np.hstack((a, b)))

[[1 2 5 6]
 [3 4 7 8]]


Функція `column_stack()` об'єднує одномірні масиви як стовпці двовимірного масиву. Для рядкыв аналогічна функція -  `row_stack()`.

In [55]:
print(np.column_stack((a, b)))

[[1 2 5 6]
 [3 4 7 8]]


In [56]:
print(np.row_stack((a, b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### <center>Розбиття масивів

Для розбиття масивів на частини використовуються функції:
- `hsplit()` - розбити масив вздовж горизонтальної вісі, вказавши або число необхідних масивів однакової форми, або номери стовпців, після яких масив розрізається;
- `vsplit()` - те саме, але за вертикальною віссю;
- `array_split()` - те саме, але можна вказати вісі, за якими виконуватиметься розбиття.

In [58]:
a = np.arange(12).reshape((2, 6))
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [59]:
# Розбити масив на 3 однакові частини за горизонтальною віссю
print(np.hsplit(a, 3))

[array([[0, 1],
       [6, 7]]), array([[2, 3],
       [8, 9]]), array([[ 4,  5],
       [10, 11]])]


In [60]:
# Розрізати масив після 3 та 4 стовпця
print(np.hsplit(a, (3, 4)))

[array([[0, 1, 2],
       [6, 7, 8]]), array([[3],
       [9]]), array([[ 4,  5],
       [10, 11]])]


### <center>Копії масивів

Під час роботи з масивами, їх дані іноді необхідно копіювати в інший масив, а іноді непотрібно. Це часто є джерелом плутанини. Можливо 3 випадки:

- Не створювати копій - просте присвоювання не створює ні копії масиву, ні копії його даних. Python передає змінювані об'єкти як посилання, тому виклики функцій також не створюють копій.

In [75]:
a = np.arange(12)
b = a
# Новий об'єкт не створено, a и b це два імені для одного и того самого об'єкта ndarray
print(b is a)

True


In [76]:
# Операції над b будуть змінювати a
b.shape = (3,4)
print(a.shape)

(3, 4)


- Поверхнева копія - різні об'єкти масивів можуть використовувати одні і ті ж дані.

In [78]:
c = a[:]
c.shape = (2,6)
# Форма а не зміниться
print(a.shape)

(3, 4)


In [81]:
c[0,4] = 1234
# Але дані а зміняться, оскільки об'єкт а та об'єкт с використовують одні і ті самі дані
print(a)

[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]


- Глибока копія - метод `copy()` створить справжню копію масиву і його даних.

In [90]:
d = a.copy()
# Створуюється новий об'єкт масиву з новими даними
print(d is a)

d[0, 0] = 9999
print(a, end="\n\n")
print(d)

False
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]

[[9999    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]


### <center>Випадкові числа в NumPy

Для створення масивів з випадковими елементами слугує модуль **numpy.random**.

Найпростіший спосіб створити масив з випадковими елементами - використати функцію `sample()` (або `random()`, або `random_sample()`, або `ranf()` - це все одна і та сама функція). Без аргументів функція повертає просто число в проміжку [0, 1), з одним цілим числом - одновимірний масив, з кортежем - масив з розмірами, зазначеними в кортежі (всі числа - з проміжку [0, 1)).

In [93]:
print(np.random.sample())

0.796677505574175


In [95]:
print(np.random.sample(3))

[0.75806689 0.34536049 0.39875985]


In [98]:
print(np.random.sample((2, 3)))

[[0.23356935 0.02325331 0.26080774]
 [0.63107246 0.19727944 0.6451033 ]]


За допомогою функції `randint()` можна створити масив з цілих чисел. Аргументи: `low, high, size`: від якого, до якого числа (не включно) і розміри масиву.

In [103]:
print(np.random.randint(0, 3, 10))

[2 0 0 1 0 2 2 0 2 0]


In [104]:
print(np.random.randint(0, 3, (2, 10)))

[[1 1 1 1 2 1 2 0 0 1]
 [1 0 2 2 0 2 2 0 0 0]]


Функція `shuffle()` - перемішати масив.

In [108]:
a = np.arange(10)
print(a)
np.random.shuffle(a)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[4 3 1 5 9 6 0 8 2 7]


Функція `choice()` - зробити випадкову вибірку елементів з масиву. Повний синтаксис: `numpy.random.choice(a, size=None, replace=True, p=None)`.
- `a`: одновимірний масив або число. Якщо це масив, буде здійснюватися вибірка з нього. Якщо число, то вибірка буде робитись з `np.arange(a)`.
- `size`: розмірність масиву. Якщо `None`, повертається одне значення.
- `replace`: якщо `True`, то одне значення може вибиратися більш ніж один раз.
- `p`: ймовірності. Це означає, що елементи можна вибирати з нерівним шансом. Якщо не задані, використовується рівномірний розподіл.

In [114]:
a = np.arange(5)
print(a)

print(np.random.choice(a, 5, p=[0.5, 0.25, 0.25, 0, 0]))

[0 1 2 3 4]
[2 0 0 0 0]


In [125]:
# Рандомне ціле число (0 або 1). Ймовірність, що випаде 0 становить 75%, що випаде 1 - 25%
print(np.random.choice(2, 1, p=[0.75, 0.25]))

[1]


### <center>Операції лінійної алгебри

Перелік деяких функцій, які реалізують корисні операції лінійної алгебри. Повний список у документації - https://numpy.org/doc/stable/reference/routines.linalg.html

- `linalg.matrix_power(M, n)` - підносить матрицю до степені n.
- `linalg.det(a)` - визначник матриці.
- `linalg.solve(a, b)` - вирішує систему лінійних рівнянь Ax = b.
- `linalg.inv(a)` - зворотня матрица.

### <center>Задачі

<u>**Задача 1**</u><br>
Створити вектор розміром 10 елементів, заповнений нулями, але п'ятий елемент дорівнює 1.

In [4]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


<u>**Задача 2**</u><br>
Створити вектор з 50 елементів та перегорнути його навпаки (останній елемент стає першим).

In [5]:
a = np.arange(50)
a = a[::-1]

<u>**Задача 3**</u><br>
Створити одиничну матрицю розміром 3х3.

In [6]:
A = np.eye(3)
print(A)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


<u>**Задача 4**</u><br>
З довільного вектора-рядка створити прямокутну матрицю.

In [8]:
B=np.arange(15).reshape((3, 5))
print(B)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


<u>**Задача 5**</u><br>
Створити масив 10x10 з випадковими значеннями, знайти мінімум і максимум.

In [9]:
A = np.random.random((10,10))
Amin, Amax = A.min(), A.max()
print(Amin, Amax)

0.00533382667282023 0.9940312484980904


<u>**Задача 6**</u><br>
Створити матрицю з 0 всередині, і 1 на границях.

In [12]:
A = np.ones((5,5))
A[1:-1,1:-1] = 0
print(A)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


<u>**Задача 7**</u><br>
Створити вектор розміром 10 елементів зі значеннями від 0 до 1 (не включаючи ні 0, ні 1)

In [14]:
A = np.linspace(0,1,12)[1:-1]
print(A)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


<u>**Задача 8**</u><br>
Відсортувати довільний вектор за зростанням.

In [16]:
A = np.random.random(10)
A.sort()
print(A)

[0.01936862 0.09203894 0.10342925 0.21492276 0.29684408 0.35378089
 0.57060986 0.67603771 0.69376457 0.99818305]


<u>**Задача 9**</u><br>
Створити програму для введення двовимірного масиву з клавіатури.

In [18]:
n = int(input('Кількість рядків: '))
m = int(input('Кількість стовпців: '))
# Створюємо нульову матрицю
a = np.zeros([n,m])  
# Заповнюємо матрицю
for i in range(n):
    for j in range(m):
        print ('Елемент матриці [',i,'][',j,']')
        a[i,j] = input('Введіть елемент: ')
print()
# Виводимо матрицю
print ('Введена така матриця:')
print(a)

Кількість рядків:  3
Кількість стовпців:  3


Елемент матриці [ 0 ][ 0 ]


Введіть елемент:  1


Елемент матриці [ 0 ][ 1 ]


Введіть елемент:  2


Елемент матриці [ 0 ][ 2 ]


Введіть елемент:  3


Елемент матриці [ 1 ][ 0 ]


Введіть елемент:  4


Елемент матриці [ 1 ][ 1 ]


Введіть елемент:  5


Елемент матриці [ 1 ][ 2 ]


Введіть елемент:  6


Елемент матриці [ 2 ][ 0 ]


Введіть елемент:  7


Елемент матриці [ 2 ][ 1 ]


Введіть елемент:  8


Елемент матриці [ 2 ][ 2 ]


Введіть елемент:  9



Введена така матриця:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


<u>**Задача 10**</u><br>
Необхідно знайти середнє арифметичне елементів масиву А, розмірністю N рядків і М стовпців.

In [20]:
n = int(input('Кількість рядків: '))
m = int(input('Кількість стовпців: '))
S = 0.0
a = np.zeros([n,m])
for i in range(n):
    for j in range(m):
        print ('Елемент матриці [',i,'][',j,']')
        a[i,j] = input('Введіть елемент: ')
        S += a[i,j]
K = n * m
C = S / K
print()
print ('Введена така матриця:')
print(a)
print()
print ('Середнє значення елементів матриці:',C)

Кількість рядків:  2
Кількість стовпців:  2


Елемент матриці [ 0 ][ 0 ]


Введіть елемент:  1


Елемент матриці [ 0 ][ 1 ]


Введіть елемент:  2


Елемент матриці [ 1 ][ 0 ]


Введіть елемент:  3


Елемент матриці [ 1 ][ 1 ]


Введіть елемент:  4



Введена така матриця:
[[1. 2.]
 [3. 4.]]

Середнє значення елементів матриці: 2.5


<u>**Задача 11**</u><br>
З двох масивів зробити матрицю Коші C та знайти її визначник. (Cij = 1 / (xi - yj))

In [22]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


<u>**Задача 12**</u><br>
Знайти найближче до заданого значення число в заданому масиві.

In [31]:
A = np.arange(50)
v = 10.6
index = (np.abs(A-v)).argmin()
print(A[index])

11


<u>**Задача 13**</u><br>
Відняти середнє з кожного рядка в матриці.

In [38]:
X = np.random.rand(2, 3)
print(X, end = "\n\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[0.31664045 0.13126718 0.63687495]
 [0.52153737 0.08639389 0.60031557]]

[[-0.04495375 -0.23032701  0.27528076]
 [ 0.11878843 -0.31635505  0.19756663]]


<u>**Задача 14**</u><br>
Дано чотиривимірний масив, порахувати суму за останніми двома осями.

In [39]:
A = np.random.randint(0,10, (3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[66 50 46 49]
 [46 44 47 67]
 [51 60 66 39]]
